name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t ghcr.io/jesusvillegas0/my-qa-app:latest .

    - name: Push Docker image
      run: |
        echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u jesusvillegas0 --password-stdin
        docker push ghcr.io/jesusvillegas0/my-qa-app:latest
